INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('두통, 발열에 효과적', '타이레놀');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('두통, 생리통, 치통에 사용', '게보린');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('면역력 강화에 도움', '비타민C 1000');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('혈액 희석제, 심혈관 질환 예방', '아스피린');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('감기 초기 증상 완화', '콜드펙스');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('장 건강 및 소화기능 개선', '프로바이오틱스');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('알레르기 증상 완화', '로페나민');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('위산 과다, 위염 증상 완화', '잔탁');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('열감기 증상에 사용', '판콜');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('수면의 질 향상', '멜라토닌');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('코감기, 코막힘 해소', '엑세라민');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('관절염 증상 완화, 연골 보호', '글루코사민');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('수면 유도 및 불면증 개선', '나이트민');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('소염진통제, 근육통 완화', '이부프로펜');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('진통제, 해열제로 사용', '파라세타몰');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('복통, 경련 완화', '노스파');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('소화불량, 위장질환 치료', '모사프리드');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('알레르기성 비염, 두드러기 치료', '지르텍');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('계절성 알레르기 증상 완화', '알레그라');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('근육 기능 개선, 변비 예방', '마그네슘');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('심혈관 건강 증진', '오메가3');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('위궤양, 위염 치료', '레바미피드');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('관절염, 성인류마티즘 치료', '셀레콕시브');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('콜레스테롤 수치 감소', '심바스타틴');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('2형 당뇨병 치료', '메트포르민');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('혈전증 예방', '리바록사반');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('고혈압 치료', '암로디핀');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('알레르기 증상 치료', '세티리진');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('고혈압, 심부전 치료', '펜토프릴');
INSERT INTO `medicine` (`information`, `medicine_name`) VALUES ('위산 분비 억제, 속쓰림 치료', '라니티딘');
